export const testIds = {
  navCalendario: "nav-calendario",
  navJogadores: "nav-jogadores",
  navTurmas: "nav-turmas",
  navDashboard: "nav-dashboard",
  navSessao: "nav-sessao",
  pageLogin: "page-login",
  inputLoginUsuario: "input-login-usuario",
  inputLoginSenha: "input-login-senha",
  buttonLogin: "button-login",
  pageCalendario: "page-calendario",
  pageDiaDetalhe: "page-dia-detalhe",
  formEvento: "form-evento",
  selectEventoTipo: "select-evento-tipo",
  selectEventoTurma: "select-evento-turma",
  buttonCriarEvento: "button-criar-evento",
  pageJogadores: "page-jogadores",
  formJogador: "form-jogador",
  buttonSalvarJogador: "button-salvar-jogador",
  pageTurmas: "page-turmas",
  formTurma: "form-turma",
  buttonSalvarTurma: "button-salvar-turma",
  pageEvento: "page-evento",
  boardEquipes: "board-equipes",
  buttonCriarPartida: "button-criar-partida",
  painelLances: "painel-lances",
  dashboardIndicadores: "dashboard-indicadores",
} as const;
