"""create usuarios

Revision ID: 15c1d0e8a253
Revises: e7b5aa2d462b
Create Date: 2025-12-08 16:35:28.800685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15c1d0e8a253'
down_revision: Union[str, None] = 'e7b5aa2d462b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('jogador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.add_column('jogadores', sa.Column('idade', sa.Integer(), nullable=True))
    op.alter_column('jogadores', 'nome',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('jogadores', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_jogadores_nome', table_name='jogadores')
    op.drop_column('jogadores', 'data_nascimento')
    op.drop_column('jogadores', 'updated_at')
    op.drop_column('jogadores', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jogadores', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('jogadores', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('jogadores', sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=True))
    op.create_index('ix_jogadores_nome', 'jogadores', ['nome'], unique=False)
    op.alter_column('jogadores', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jogadores', 'nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('jogadores', 'idade')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
