"""create turmas e turma_participantes

Revision ID: 8d327626e57b
Revises: 15c1d0e8a253
Create Date: 2025-12-08 18:22:14.653822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d327626e57b'
down_revision: Union[str, None] = '15c1d0e8a253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=True),
    sa.Column('horario_inicio', sa.Time(), nullable=True),
    sa.Column('horario_fim', sa.Time(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turmas_id'), 'turmas', ['id'], unique=False)
    op.create_table('turma_participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('pode_jogar', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turma_participantes_id'), 'turma_participantes', ['id'], unique=False)
    op.alter_column('jogadores', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('usuarios', 'papel',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('usuarios', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('usuarios', 'papel',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('jogadores', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_turma_participantes_id'), table_name='turma_participantes')
    op.drop_table('turma_participantes')
    op.drop_index(op.f('ix_turmas_id'), table_name='turmas')
    op.drop_table('turmas')
    # ### end Alembic commands ###
