"""create dias e aulas

Revision ID: b708ce6766e2
Revises: 8d327626e57b
Create Date: 2025-12-08 19:09:09.638268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b708ce6766e2'
down_revision: Union[str, None] = '8d327626e57b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.Column('treino_cancelado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    op.create_index(op.f('ix_dias_id'), 'dias', ['id'], unique=False)
    op.create_table('aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=True),
    sa.Column('horario_fim', sa.Time(), nullable=True),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['dia_id'], ['dias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aulas_id'), 'aulas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aulas_id'), table_name='aulas')
    op.drop_table('aulas')
    op.drop_index(op.f('ix_dias_id'), table_name='dias')
    op.drop_table('dias')
    # ### end Alembic commands ###
