"""create jogadores

Revision ID: e7b5aa2d462b
Revises: 
Create Date: 2025-12-08 16:25:43.129024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b5aa2d462b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jogadores_id'), 'jogadores', ['id'], unique=False)
    op.create_index(op.f('ix_jogadores_nome'), 'jogadores', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jogadores_nome'), table_name='jogadores')
    op.drop_index(op.f('ix_jogadores_id'), table_name='jogadores')
    op.drop_table('jogadores')
    # ### end Alembic commands ###
