persistence true
persistence_location /mosquitto/data/
log_dest stdout

# MQTT TCP (backend publica aqui)
listener 1883
protocol mqtt

# MQTT over WebSocket (frontend conecta aqui)
listener 8083
protocol websockets

allow_anonymous true
